# arxivの学問領域の指定
subject: 'cs'

# 検索キーワード
keywords:
        image segmentation: 3
        semantic segmentation: 3
        depth estimation: 3
        differentiable rendering: 3
        object tracking: 3
        3d animation: 2
        human body: 2
        depth: 1
        object tracking: 1
        audio synthesis: 1
        video generation: 1